### ISSUE TITLE
Deprecated plugin as api no longer exists

### ISSUE THREAD

**Issue by hybridwebdev** [digitoimistodude/dude-insta-feed#2]
So you should probably remove this repo, as the instagram api no longer exists. Hopefully people will see this and won't waste their time. 

TLDR: This no longer works as FB removed the api.

**Comment by timiwahalahti** [comment]
Hi! Sorry for little late response :)

Instagram API actually exists and this plugin still works. Facebook has announced that they will [depreciate the used endpoint in early 2020](https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/).

The only catch is that the application needs to be created with as the same user as you want to get the images from - as said in [documentation](https://github.com/digitoimistodude/dude-insta-feed#usage-example-for-displaying-user-feed).

> Please note that application must be registered with that exact user account you want to pull images from!

There is plans to change this plugin to work with new [Instagram Graph API](https://developers.facebook.com/products/instagram/), but no work for that has yet been stared.

**Comment by jake-101** [comment]
I rewrote the plugin to use the Graph API. It's not pretty code (to say the least), but putting in a Graph API token will make it work.
[https://github.com/jake-101/ig-graph-feed](https://github.com/jake-101/ig-graph-feed)

**Comment by rollecode** [comment]
Nice! Your plugin is now mentioned in our README.md. 👍

**Comment by jake-101** [comment]
Awesome! I'll refactor it and write better docs this weekend or next week to make it easier for new users. It is pretty plug and play on the front end if you already have the plugin setup before.
